"""rename address

Revision ID: 24185c31cb15
Revises: 6bc48cdfeb73
Create Date: 2024-06-26 17:45:15.798261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24185c31cb15'
down_revision = '6bc48cdfeb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
