"""rename department

Revision ID: 6bc48cdfeb73
Revises: c2b5be03a159
Create Date: 2024-06-26 17:36:43.620239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc48cdfeb73'
down_revision = 'c2b5be03a159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
